project:
  type: website
  output-dir: "docs"
  resources:
    - "/datasets"
    
website:
  title: "Medical Statistics"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Labs week 1"
        menu:
          - text: "R"
            href: R_lab1.qmd
          - text: "SPSS"
            href: SPSS_lab1.qmd
      - text: "Labs week 2"
        menu:
          - text: "R"
            href: R_lab2.qmd
          - text: "SPSS"
            href: SPSS_lab2.qmd      
      - text: "Answers"
        menu:
          - text: "Week 1"
            href: lab1_answers.qmd
          - text: "Week 2"
            href: lab2_answers.qmd
      - text: "Datasets"
        menu:
          - text: "lowbwt.sav"
            href: datasets/lowbwt.sav
          - text: "ex5_6.sav"
            href: datasets/ex5_6.sav
          - text: "pockets_paired.sav"
            href: datasets/pockets_paired.sav
          - text: "heart_disease_cleveland.sav"
            href: datasets/heart_disease_cleveland.sav
          - text: "pockets.sav"
            href: datasets/pockets.sav
          - text: "whas500.sav"
            href: datasets/whas500.sav  
          - text: "GvHD.sav"
            href: datasets/GvHD.sav 
          - text: "Ex9_1.sav"
            href: datasets/Ex9_1.sav
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

